### ISSUE TITLE
 Peer failed to perform TLS handshake: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by zany130** [syncthing-gtk/syncthing-gtk#86]
On a steam deck running bazzite, I get the following when loading the application.

I first tried the flatpak and go this error, then tried installing syncthing-gtk through a arch distrobox and after copying my config from the flatpak over it worked at first but after rebooting I started getting the same error

```
syncthing-gtk

(syncthing-gtk:63370): Gtk-WARNING **: 19:27:13.761: Locale not supported by C library.
    Using the fallback 'C' locale.

** (syncthing-gtk:63370): WARNING **: 19:27:13.910: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.910: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead

** (syncthing-gtk:63370): WARNING **: 19:27:13.911: expected enumeration type void, but got PyGLibOptionArg instead
I StatusIcon    Using backend StatusIconGTK3 (primary)

(syncthing-gtk:63370): Gtk-CRITICAL **: 19:27:14.111: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
E HTTP          g-tls-error-quark: Peer failed to perform TLS handshake: The TLS connection was non-properly terminated. (3)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/syncthing_gtk/http.py", line 47, in _connected
    self._connection = self.connect_to_service_finish(results)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-tls-error-quark: Peer failed to perform TLS handshake: The TLS connection was non-properly terminated. (3)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/syncthing_gtk/http.py", line 47, in _connected
    self._connection = self.connect_to_service_finish(results)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-tls-error-quark: Peer failed to perform TLS handshake: The TLS connection was non-properly terminated. (3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/syncthing_gtk/http.py", line 54, in _connected
    self._error(e)
  File "/usr/lib/python3.12/site-packages/syncthing_gtk/http.py", line 199, in _error
    self._error_callback(exception, self._command, *self._callback_data)
  File "/usr/lib/python3.12/site-packages/syncthing_gtk/daemon.py", line 752, in _syncthing_cb_config_error
    self.emit("connection-error", Daemon.TLS_UNSUPPORTED, exception.message, exception)
                                                          ^^^^^^^^^^^^^^^^^
AttributeError: 'TLSUnsupportedException' object has no attribute 'message'
```

**Comment by zany130** [comment]
It appears to be a conflict between synching and decky plugin loader which also runs on port 8080. 

I configured synching to run on port 8384 and I still get this error. 


Only after disabling https (no idea what https has to do with decky) in synching it works.
